### PR TITLE
Working example with Mapbox Geocoder

### PR DESCRIPTION
**Pull request by awolfe76**
This works now but is using the Mapbox Geocoder with the idea of swapping that out with ours.

You can see the example here: 
http://awolfe76.github.io/grasshopper-ui/

### CODE REVIEW

**Comment by wpears** [comment]
I'm going to rebase this ontop of the now squashed master and include it as a PR to your repo. Trying to keep the extraneous commits from the template out of our history

**Comment by wpears** [comment]
My idea proved a little silly, but it will be fixed soon with some force pushing.. don't fork andrew's repo anytime soon unless you like merge conflicts

(!Fixed!)

**Comment by awolfe76** [comment]
@wpears
I **think** this is ok now. Preview of updates here - http://awolfe76.github.io/grasshopper-ui/

**Comment by wpears** [comment]
We're getting closer! Check out http://wpears.github.io/grasshopper-ui/src/

**Comment by wpears** [comment]
See https://github.com/cfpb/grasshopper-ui/pull/12

**Pull request closed without merging**
